[package]
name = "question3"
version = "0.1.0"
authors = ["usmanqau12 <usman.qau12@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
q3 = {path="q3"}
